version: '3.8'

services:
  backend:
    build: ./gym-rest-api
    image: gym-rest-1.0.0
    container_name: gym-rest
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    env_file:
      - .env
    image: gym-frontend-1.0.0
    container_name: gym-frontend
    ports:
      - "127.0.0.1:3000:3000"

  mongo:
    image: mongo:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-gym-db:/data/db
      - ./gym-rest-api/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  mongo-gym-db: