version: '3.8'

services:
  backend:
#    поменять директорию
    build: ./gym-rest-api
    image: gym-rest-1.0.0
    container_name: gym-rest
    env_file:
      - .env
#    должны маппить потому что фронтенд будет посылать запросы на машину нашу
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: gym-frontend-1.0.0
    container_name: gym-frontend
#    добавить env для порта фронта
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    restart: always
    env_file:
      - .env
#    ports: можно не прописывать, т.к. в сети докера и так доступна будет?
#      - "${DATABASE_PORT_MAPPING}:27017"
    expose:
      - "27017"
    volumes:
      - mongo-gym-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  mongo-gym-db: